version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    links:
      - mailhog:mailhog
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"