---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: quay.io/kissj/php
          tag: latest
    
    
inputs:
  - name: kissj-app
      
run:
  path: composer 
  args:
  - cs
  - --working-dir=kissj-app
  - --no-interaction
 


