---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: composer
          tag: 2.1.9
    
inputs:
  - name: kissj-app
      
run:
  path: composer 
  args:
  - cs
  - --working-dir=kissj-app
  - --no-interaction
 


