---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: alpine/helm
          tag: latest
          
    
inputs:
  - name: kissj-app

run:
  path: helm
  args:
  - lint
  - kissj-app/deploy/helm/charts/kissj
  
