---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: alpine/helm
          tag: latest
          
    
inputs:
  - name: kissj-app
outputs: 
  - name: helm-chart
      
run:
  path: helm
  args:
  - package
  - kissj-app/deploy/helm/charts/kissj
  - --destination=helm-chart

  
