---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: quay.io/kissj/php
          tag: latest
    
          
    
inputs:
  - name: kissj-app
outputs: 
  - name: kissj-app
params:
  COMPOSER_MEMORY_LIMIT: "256M"    
run:
  path: composer 
  args:
  - install
  - --working-dir=kissj-app
  - --no-interaction
