---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: overtrue/phplint
          #tag: 8.0
          
    
inputs:
  - name: kissj-app
      
run:
  path: /root/.composer/vendor/bin/phplint 
  args:
  - kissj-app
  - --exclude=vendor
  - --warning