---
platform: linux

image_resource:
        type: registry-image
        source:
          repository: quay.io/kissj/php
          tag: latest
    
    
inputs:
  - name: kissj-app

params:
  COMPOSER_MEMORY_LIMIT: "512M"

run:
  path: composer 
  args:
  - test
  - --working-dir=kissj-app
  - --no-interaction
  
