apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-sessions
  annotations:
    cas.openebs.io/config: |
      - name: FilePermissions
        data:
          GID: "120"
          mode: "g+s"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.php.volume.size | quote }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.php.volume.storageclass | quote }}