name: Staging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      envName:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: staging
      envUrl:
        description: 'URL of the environment'
        required: true
        type: string
        default: 'https://staging.kissj.net'

jobs:

  staging:
    runs-on: ubuntu-latest

    steps:
      - name: run-tests
        uses: SkautDevs/kissj/.github/workflows/tests.yaml@master
        with:
          envName: ${{ github.event.inputs.envName }}
          envUrl: ${{ github.event.inputs.envUrl }}

      - name: build-images
        uses: SkautDevs/kissj/.github/workflows/build.yaml@master
        with:
          envName: 'staging'
          envUrl: 'staging.kissj.net'
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }} 

      - name: deploy
        uses: SkautDevs/kissj/.github/workflows/deploy.yaml@master
        with:
          envName: 'staging'
          envUrl: 'staging.kissj.net'
