name: Staging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      envName:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: staging
      envUrl:
        description: 'URL of the environment'
        required: true
        type: string
        default: 'https://staging.kissj.net'

jobs:

  staging-test:
    uses: SkautDevs/kissj/.github/workflows/tests.yaml@master

  staging-build:
    needs: staging-test
    uses: SkautDevs/kissj/.github/workflows/build.yaml@master
    with:
      envName: 'staging'

    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }} 

  staging-deploy:
    needs: staging-build
    uses: SkautDevs/kissj/.github/workflows/deploy.yaml@master
    with:
      envName: 'staging'
      envUrl: 'staging.kissj.net'
