# .github/workflows/deploy.yml
name: Deploy to Kubernetes 
on: 
  workflow_call:
    inputs:
      envName:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: staging
      
      envUrl:
        description: 'URL of the environment'
        required: true
        type: string
        default: 'https://staging.kissj.net'

jobs:
  deploy-stage:
    name: Deploy Staging to Kubernetes
    runs-on: 'ubuntu-latest'
    environment: 
      name: ${{ inputs.envName }}
      url: ${{ inputs.envUrl }}
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        release: kissj-${{ inputs.envName }}
        namespace: 'kissj-${{ inputs.envName }}'
        chart: 'deploy/helm/charts/kissj'
        helm: 'helm3'
        token: '${{ github.token }}'
        secrets: ${{ toJSON(secrets.test_secret) }}'
        values: |
          postgres:
            incluster: true
            username: dummy
            password: dummy
            dbname: kissj
            host: dummy
          caddy:
            image:
              name: quay.io/kissj/caddy-ubi
              tag: ${{ inputs.envName}}-${{ github.sha }}
          php:
            image:
              name: quay.io/kissj/php-ubi
              tag: ${{ inputs.envName}}-${{ github.sha }}
          app:
            url: ${{ inputs.envUrl }}
            
            s3:
              key: dummy
              secret: dummy
              region: dummy
              endpoint: dummy
              bucket: dummy
            
            mail:
              server: dummy
              port: 587
              encryption: tls
              username: dummy
              password: dummy
            
            adminer:
              username: dummy
              password: dummy    

      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
